# Generated by Django 5.1.2 on 2024-11-10 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_lesson_course'),
        ('users', '0004_paymant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paymant',
            new_name='Payment',
        ),
    ]
