# Generated by Django 5.1.2 on 2024-11-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="идентификатор платежа",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_url",
            field=models.URLField(
                blank=True, max_length=400, null=True, verbose_name="ссылка на оплату"
            ),
        ),
    ]
