# Generated by Django 5.1.2 on 2024-11-10 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_lesson_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберете курс, к которому относится урок",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.course",
                verbose_name="Курс к которому относится урок",
            ),
        ),
    ]
