# Generated by Django 5.1.2 on 2024-11-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="link",
            field=models.URLField(blank=True, null=True, verbose_name="link"),
        ),
    ]
